
name: 'dtc_de_final'
version: '1.0.0'
config-version: 2

profile: 'dtc_de_final'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dtc_de_final:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view

vars:
  assessment_years: [2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015]